name: Build CI

# Permissions required for triggering workflows
permissions:
  contents: write
  actions: write

on:
  push:
    
  pull_request:
   

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint

  test:
    name: Run Automated Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  manual-approval-pr:
    name: Manual Approval for Pull Request
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: github.event_name == 'pull_request'
    steps:
      - name: Notify for manual approval
        run: echo "PR Tests Passed. Please approve and merge to trigger the CD workflow."

  trigger-cd:
    name: Trigger CD Workflow After Merge
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: github.event_name == 'push'  # Trigger CD only after push to main
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger CD workflow
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "cd.yml",
              ref: context.ref
            })
